apiVersion: hsts.aspera.ibm.com/v1
kind: IbmAsperaHsts
metadata:
  name: aspera-hsts
  labels:
    app.kubernetes.io/instance: ibm-aspera-hsts
    app.kubernetes.io/managed-by: ibm-aspera-hsts
    app.kubernetes.io/name: ibm-aspera-hsts
  namespace: cp4i
spec:
  license:
    accept: false
    key: licencezzz
    use: CloudPakForIntegrationNonProduction
  hostPorts:
    ascp: 33001
  deployments:
    default:
      replicas: 1
  storages:
    - claimName: hsts-transfer-pvc
      class: rook-ceph-block
      deleteClaim: true
      mountPath: /data/
      size: 20Gi
  redis:
    environment:
      adminPassword: Passw0rd
    persistence:
      enabled: true
      storageClass: rook-cephfs
    version: 6.0.16
  services:
    httpProxy:
      type: ClusterIP
    tcpProxy:
      type: LoadBalancer
  version: 4.4.1
