apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}-aspera-hsts-pvc
  namespace: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {###PROVIDE_YOUR_STORAGECLASSFS_HERE###}
