apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}-ace-is
  namespace: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}  
  labels: {}
spec:
  adminServerSecure: false
  barURL: >-
    https://github.com/amarIBM/hello-world/raw/master/HttpEchoApp.bar
  configurations:
    - {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}-ace-configuration
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: {###PROVIDE_YOUR_ACE_LICENCE_CP4X_HERE###}
    use: AppConnectEnterpriseProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '12.0'
