apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsts-transfer-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: hsts-transfer-pvc-gid
