apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: quickstart
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-RJON-CCAT5F
    use: nonproduction
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: cp4i-datapower-secret
  storage:
    - path: /data/dp
      type: persistent
      class: rook-cephfs
  replicas: 1
  version: 10.5-lts
#--------------------------------------------------------------------------
#Alexander
apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: datapower
  namespace: integration
spec:
  license:
    accept: true
    license: L-RJON-CCAT5F
    use: nonproduction
  resources:
    limits:
      cpu: '8'
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: datapower-secret
  storage:
    - type: persistent
      class: ocs-storagecluster-ceph-rbd
      deleteClaim: true
      path: /opt/ibm/datapower/drouter/config
      size: 10Gi
    - type: persistent
      class: ocs-storagecluster-ceph-rbd
      deleteClaim: true
      path: /opt/ibm/datapower/drouter/temporary
      size: 5Gi
  replicas: 1
  updateStrategy:
    mode: automatic
  version: 10.5-lts
  runAsRoot: true
  createServiceBinding: automatic
